### ISSUE TITLE
No longer supported by Google

### ISSUE THREAD

**Issue by nickdaugherty** [jaredhanson/passport-google#35]
Google has officially stopped supporting OpenID as of April 20th, 2015, and all requests are redirected to a [static error page](https://support.google.com/accounts/answer/6206245?p=openid&rd=1).

The readme should be updated to reflect the current status of support, and a recommendation to use [Passport-Google-OAuth](https://github.com/jaredhanson/passport-google-oauth) instead.

https://developers.google.com/identity/protocols/OpenID2Migration#shutdown-timetable

**Comment by alexjab** [comment]
:+1:

**Comment by auxiliary** [comment]
:+1: I wish I had seen this sooner. The README should really be updated.

**Comment by saadtazi** [comment]
+1

**Comment by JohnMcLear** [comment]
+1

**Comment by Palmer11** [comment]
+1

**Comment by prtksxna** [comment]
+1

**Comment by gogromat** [comment]
oh come on...+1

**Comment by imatveev** [comment]
+1. Update readme!

**Comment by zacg** [comment]
+1
