### ISSUE TITLE
Windows Azure /auth/google/return

### ISSUE THREAD

**Issue by codercatdev** [jaredhanson/passport-google#6]
On localhost this works, but not on Windows Azure.

var express = require('express')
  , engine = require('ejs-locals')
  , passport = require('passport')
  , util = require('util')
  , GoogleStrategy = require('passport-google').Strategy;

// Passport session setup.
//   To support persistent login sessions, Passport needs to be able to
//   serialize users into and deserialize users out of the session.  Typically,
//   this will be as simple as storing the user ID when serializing, and finding
//   the user by ID when deserializing.  However, since this example does not
//   have a database of user records, the complete Google profile is serialized
//   and deserialized.
passport.serializeUser(function(user, done) {
  done(null, user);
});

passport.deserializeUser(function(obj, done) {
  done(null, obj);
});

// Use the GoogleStrategy within Passport.
//   Strategies in passport require a `validate` function, which accept
//   credentials (in this case, an OpenID identifier and profile), and invoke a
//   callback with a user object.
passport.use(new GoogleStrategy({
    returnURL: 'http://nodejs-test.azurewebsites.net/auth/google/return',
    realm: 'http://nodejs-test.azurewebsites.net/'
    // returnURL: 'http://localhost:1337/auth/google/return',
    // realm: 'http://localhost:1337/'
  },
  function(identifier, profile, done) {
    // asynchronous verification, for effect...
    process.nextTick(function () {

```
  // To keep the example simple, the user's Google profile is returned to
  // represent the logged-in user.  In a typical application, you would want
  // to associate the Google account with a user record in your database,
  // and return that user instead.
  profile.identifier = identifier;
  return done(null, profile);
});
```

  }
));

var app = express();
// use ejs-locals
app.engine('ejs', engine);
// configure Express
app.configure(function() {
  app.set('views', __dirname + '/views');
  app.set('view engine', 'ejs');
  app.set('port', process.env.PORT || 1337);
  app.use(express.logger());
  app.use(express.cookieParser());
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.session({ secret: 'keyboard cat' }));
  // Initialize Passport!  Also use passport.session() middleware, to support
  // persistent login sessions (recommended).
  app.use(passport.initialize());
  app.use(passport.session());
  app.use(app.router);
  app.use(express.static(__dirname + '/../../public'));
});

app.get('/', function(req, res){
  res.render('index', { user: req.user, title: 'AJONP - Login'});
});

app.get('/account', ensureAuthenticated, function(req, res){
  res.render('account', { user: req.user });
});

app.get('/login', function(req, res){
  res.render('login', { user: req.user });
});

// GET /auth/google
//   Use passport.authenticate() as route middleware to authenticate the
//   request.  The first step in Google authentication will involve redirecting
//   the user to google.com.  After authenticating, Google will redirect the
//   user back to this application at /auth/google/return
app.get('/auth/google', 
  passport.authenticate('google', { failureRedirect: '/login' }),
  function(req, res) {
    res.redirect('/');
  });

// GET /auth/google/return
//   Use passport.authenticate() as route middleware to authenticate the
//   request.  If authentication fails, the user will be redirected back to the
//   login page.  Otherwise, the primary route function function will be called,
//   which, in this example, will redirect the user to the home page.
app.get('/auth/google/return', 
  passport.authenticate('google', { failureRedirect: '/login' }),
  function(req, res) {
    res.redirect('/');
  });

app.get('/logout', function(req, res){
  req.logout();
  res.redirect('/');
});

// Simple route middleware to ensure user is authenticated.
//   Use this route middleware on any resource that needs to be protected.  If
//   the request is authenticated (typically via a persistent login session),
//   the request will proceed.  Otherwise, the user will be redirected to the
//   login page.
function ensureAuthenticated(req, res, next) {
  if (req.isAuthenticated()) { return next(); }
  res.redirect('/login')
}

**Comment by danny8002** [comment]
https://github.com/jaredhanson/passport-google/issues/6

**Comment by danny8002** [comment]
Just want somebody who read here to know the solution ( i got crazed by this issue)
1. Microsoft Azure (app service, cloud service ) have this limitation see [azure-subscription-service-limits](https://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/)
2. For Azure website, i find no solution. but for Cloud Service, you can modify your web.cloud.config [configure-request-url-length-Azure-Cloud-Service](http://stackoverflow.com/questions/11636386/how-to-configure-the-web-config-to-allow-requests-of-any-length)
